version: '3.8'
services:
  app:
    build: .
    container_name: teerayut_app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: password123
      DB_NAME: teerayut_dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: teerayut_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: teerayut_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: